name: porter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  http:
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  another_flushbar: ^1.12.30
  url_launcher: ^6.3.1
  share_plus: ^10.1.3
#  flutter_html:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/

#example:
fonts:
  - family: Poppins
    fonts:
      - asset: fonts/poppins_medium.ttf
        weight: 500
      - asset: fonts/Poppins-Regular.ttf
        weight: 400
      - asset: fonts/Poppins-SemiBold.ttf
        weight: 600
        style: italic

#      - family: Trajan Pro
#        fonts:
#      - asset: fonts/TrajanPro.ttf
#      - asset: fonts/TrajanPro_Bold.ttf
#        weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/to/font-from-package
